"""empty message

Revision ID: 1a09bb963171
Revises: 30be442b4d56
Create Date: 2018-08-09 16:07:00.838311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a09bb963171'
down_revision = '30be442b4d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('grade_ibfk_1', 'grade', type_='foreignkey')
    op.drop_constraint('grade_ibfk_2', 'grade', type_='foreignkey')
    op.add_column('product', sa.Column('PE_ratio', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('product', sa.Column('amount', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('last_price', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('product', sa.Column('price', sa.DECIMAL(precision=5, scale=2), nullable=False))
    op.add_column('product', sa.Column('total_increase', sa.DECIMAL(precision=6, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'total_increase')
    op.drop_column('product', 'price')
    op.drop_column('product', 'last_price')
    op.drop_column('product', 'amount')
    op.drop_column('product', 'PE_ratio')
    op.create_foreign_key('grade_ibfk_2', 'grade', 'front_user', ['uid'], ['id'])
    op.create_foreign_key('grade_ibfk_1', 'grade', 'product', ['pid'], ['id'])
    # ### end Alembic commands ###
